/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CaseVolunteer;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CounsellingOrganization;
import business.Organization.PsychiatricOrganization;
import business.Organization.HospitalOrganization;
import business.Organization.LegalOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.CounsellorWorkRequest;
import business.WorkQueue.DrWorkRequest;
import business.WorkQueue.PsychiatristWorkRequest;
import business.WorkQueue.CaseReporterWorkRequest;
import business.WorkQueue.Child;
import business.WorkQueue.Children;
import business.WorkQueue.LawyerWorkRequest;
import business.WorkQueue.RehabilitationCaretakerWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dhaval
 */
public class CaseReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaseReportJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    CaseReporterWorkRequest request;
    UserAccount userAccount;
    Network network;
    public CaseReportJPanel(JPanel userProcessContainer, EcoSystem system, CaseReporterWorkRequest request,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.request = request;
        this.userAccount = userAccount;
        this.network = network;
        PopulateInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JPanel();
        lblVictimName = new javax.swing.JLabel();
        lblRelation = new javax.swing.JLabel();
        lblTypeofAssault = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        timejLabel = new javax.swing.JLabel();
        lblMoreDetail = new javax.swing.JLabel();
        lblSuspect = new javax.swing.JLabel();
        lblNameSuspect = new javax.swing.JLabel();
        txtVictimName = new javax.swing.JTextField();
        txtNameofSuspect = new javax.swing.JTextField();
        txtMoreDetails = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtVolunteerName = new javax.swing.JTextField();
        txtTypeofAssault = new javax.swing.JTextField();
        txtDateofIncident = new javax.swing.JTextField();
        txtSuspect = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblVictimInfo = new javax.swing.JLabel();
        btnReqLawyer = new javax.swing.JButton();
        btnReqCounsellar = new javax.swing.JButton();
        btnReqDoc = new javax.swing.JButton();
        btnReqPsych = new javax.swing.JButton();
        btnReqRehab = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setBackground(new java.awt.Color(255, 255, 255));

        lblVictimName.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblVictimName.setText("Victim name : ");

        lblRelation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblRelation.setText("Relation/ Volunteer name: ");

        lblTypeofAssault.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblTypeofAssault.setText("Type of child Assault : ");

        lblLocation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLocation.setText("Location of Incident :");

        timejLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        timejLabel.setText("Date of Incident :");

        lblMoreDetail.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblMoreDetail.setText("More Details : ");

        lblSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblSuspect.setText("Suspect :");

        lblNameSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblNameSuspect.setText("Name of Suspect : ");

        txtVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVictimNameActionPerformed(evt);
            }
        });

        txtNameofSuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameofSuspectActionPerformed(evt);
            }
        });

        txtVolunteerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerNameActionPerformed(evt);
            }
        });

        txtTypeofAssault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeofAssaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblDateLayout = new javax.swing.GroupLayout(lblDate);
        lblDate.setLayout(lblDateLayout);
        lblDateLayout.setHorizontalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVictimName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTypeofAssault, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRelation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblMoreDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(lblSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNameofSuspect)
                    .addComponent(txtTypeofAssault, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateofIncident, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuspect, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txtVolunteerName)
                    .addComponent(txtVictimName)
                    .addComponent(txtMoreDetails, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(84, 84, 84))
        );
        lblDateLayout.setVerticalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDateLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVictimName)
                    .addComponent(txtVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRelation)
                    .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeofAssault)
                    .addComponent(txtTypeofAssault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateofIncident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoreDetail)
                    .addComponent(txtMoreDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuspect)
                    .addComponent(txtSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameSuspect)
                    .addComponent(txtNameofSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 62, -1, -1));

        btnBack.setBackground(new java.awt.Color(51, 102, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, 82, -1));

        lblVictimInfo.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        lblVictimInfo.setForeground(new java.awt.Color(51, 102, 255));
        lblVictimInfo.setText("Victim Information");
        jPanel1.add(lblVictimInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 14, 342, 42));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        btnReqLawyer.setBackground(new java.awt.Color(51, 102, 255));
        btnReqLawyer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqLawyer.setForeground(new java.awt.Color(255, 255, 255));
        btnReqLawyer.setText("Request Lawyer");
        btnReqLawyer.setBorderPainted(false);
        btnReqLawyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqLawyerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqLawyerMouseEntered(evt);
            }
        });
        btnReqLawyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqLawyerActionPerformed(evt);
            }
        });
        add(btnReqLawyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 170, 38));

        btnReqCounsellar.setBackground(new java.awt.Color(51, 102, 255));
        btnReqCounsellar.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqCounsellar.setForeground(new java.awt.Color(255, 255, 255));
        btnReqCounsellar.setText("Request Counsellar");
        btnReqCounsellar.setBorderPainted(false);
        btnReqCounsellar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqCounsellarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqCounsellarMouseEntered(evt);
            }
        });
        btnReqCounsellar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqCounsellarActionPerformed(evt);
            }
        });
        add(btnReqCounsellar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 200, 41));

        btnReqDoc.setBackground(new java.awt.Color(51, 102, 255));
        btnReqDoc.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnReqDoc.setText("Request Doctor");
        btnReqDoc.setBorderPainted(false);
        btnReqDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqDocMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqDocMouseEntered(evt);
            }
        });
        btnReqDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqDocActionPerformed(evt);
            }
        });
        add(btnReqDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 170, 41));

        btnReqPsych.setBackground(new java.awt.Color(51, 102, 255));
        btnReqPsych.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqPsych.setForeground(new java.awt.Color(255, 255, 255));
        btnReqPsych.setText("Psychiatrist");
        btnReqPsych.setBorderPainted(false);
        btnReqPsych.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqPsychMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqPsychMouseEntered(evt);
            }
        });
        btnReqPsych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqPsychActionPerformed(evt);
            }
        });
        add(btnReqPsych, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 152, 38));

        btnReqRehab.setBackground(new java.awt.Color(51, 102, 255));
        btnReqRehab.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqRehab.setForeground(new java.awt.Color(255, 255, 255));
        btnReqRehab.setText("Request Rehabilitation");
        btnReqRehab.setBorderPainted(false);
        btnReqRehab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqRehabMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqRehabMouseEntered(evt);
            }
        });
        btnReqRehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqRehabActionPerformed(evt);
            }
        });
        add(btnReqRehab, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 200, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReqLawyerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqLawyerMouseEntered
        btnReqCounsellar.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerMouseEntered

    private void btnReqLawyerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqLawyerMouseExited
        btnReqLawyer.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerMouseExited

    private void btnReqLawyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqLawyerActionPerformed

        LawyerWorkRequest legalawyerequest = new LawyerWorkRequest();
        legalawyerequest.setStatus("Waiting");
        legalawyerequest.setSender(userAccount);
        legalawyerequest.setCaseReporterWorkRequest(request);
        legalawyerequest.getCaseReporterWorkRequest().setLawyerWorkRequest(legalawyerequest);
        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.Justice);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LegalOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getLawyerworkRequestList().add(legalawyerequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getLawyerworkRequestList().add(legalawyerequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Lawyer.");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerActionPerformed

    private void btnReqPsychMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqPsychMouseEntered
        btnReqPsych.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqPsychMouseEntered

    private void btnReqPsychMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqPsychMouseExited
        btnReqPsych.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqPsychMouseExited

    private void btnReqPsychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqPsychActionPerformed
        PsychiatristWorkRequest psychrequest = new PsychiatristWorkRequest();
        psychrequest.setStatus("Waiting");
        psychrequest.setSender(userAccount);
        psychrequest.setCaseReporterWorkRequest(request);
        psychrequest.getCaseReporterWorkRequest().setHpWorkRequest(psychrequest);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.NGO);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            System.out.println("ex"+organization.getName());
            if (organization instanceof PsychiatricOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getPsychiatristWorkRequestList().add(psychrequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getPsychiatristWorkRequestList().add(psychrequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Psychiatrist");

    }//GEN-LAST:event_btnReqPsychActionPerformed

    private void txtVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVictimNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVictimNameActionPerformed

    private void txtNameofSuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameofSuspectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameofSuspectActionPerformed

    private void txtVolunteerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerNameActionPerformed

    private void txtTypeofAssaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeofAssaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeofAssaultActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CaseVolunteerPJPanel sysAdminwjp = (CaseVolunteerPJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReqDocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqDocMouseEntered
        btnReqDoc.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqDocMouseEntered

    private void btnReqDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqDocMouseExited
        btnReqDoc.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqDocMouseExited

    private void btnReqDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqDocActionPerformed
        DrWorkRequest docrequest = new DrWorkRequest();
        docrequest.setStatus("Waiting");
        docrequest.setSender(userAccount);
        docrequest.setCaseReporterWorkRequest(request);
        docrequest.getCaseReporterWorkRequest().setDoctorWorkRequest(docrequest);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.Wellness);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HospitalOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getDoctorworkRequestList().add(docrequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getDoctorworkRequestList().add(docrequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Hosptital.");
    }//GEN-LAST:event_btnReqDocActionPerformed

    private void btnReqCounsellarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCounsellarMouseEntered
        btnReqCounsellar.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqCounsellarMouseEntered

    private void btnReqCounsellarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCounsellarMouseExited
        btnReqCounsellar.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqCounsellarMouseExited

    private void btnReqCounsellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqCounsellarActionPerformed
        CounsellorWorkRequest counsellarreq = new CounsellorWorkRequest();
        counsellarreq.setStatus("Waiting");
        counsellarreq.setSender(userAccount);
        counsellarreq.setHswr(request);
        counsellarreq.getHswr().setCounsellorWorkRequest(counsellarreq);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.Wellness);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CounsellingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getCounsellarworkRequestList().add(counsellarreq);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getCounsellarworkRequestList().add(counsellarreq);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Counsellar");
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReqCounsellarActionPerformed

    private void btnReqRehabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqRehabMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqRehabMouseExited

    private void btnReqRehabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqRehabMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqRehabMouseEntered

    private void btnReqRehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqRehabActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReqRehabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReqCounsellar;
    private javax.swing.JButton btnReqDoc;
    private javax.swing.JButton btnReqLawyer;
    private javax.swing.JButton btnReqPsych;
    private javax.swing.JButton btnReqRehab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lblDate;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMoreDetail;
    private javax.swing.JLabel lblNameSuspect;
    private javax.swing.JLabel lblRelation;
    private javax.swing.JLabel lblSuspect;
    private javax.swing.JLabel lblTypeofAssault;
    private javax.swing.JLabel lblVictimInfo;
    private javax.swing.JLabel lblVictimName;
    private javax.swing.JLabel timejLabel;
    private javax.swing.JTextField txtDateofIncident;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMoreDetails;
    private javax.swing.JTextField txtNameofSuspect;
    private javax.swing.JTextField txtSuspect;
    private javax.swing.JTextField txtTypeofAssault;
    private javax.swing.JTextField txtVictimName;
    private javax.swing.JTextField txtVolunteerName;
    // End of variables declaration//GEN-END:variables
    
    private void PopulateInfo() {
        txtVictimName.setText(request.getChildName());
        txtVolunteerName.setText(request.getRelation());
        txtTypeofAssault.setText(request.getAssaultType());
        txtLocation.setText(request.getLocation());
        txtDateofIncident.setText(request.getDoi().toString());
        txtMoreDetails.setText(request.getMoredetails());
        txtSuspect.setText(request.getSuspecttype());
        txtNameofSuspect.setText(request.getNameofsuspect());
        
        
    }
    

}
